### ISSUE TITLE
Text prompts for DDIM inversion

### ISSUE THREAD

**Issue by zichongc** [genforce/freecontrol#10]
Hi, 
I appreciate your nice work! However, I find myself a bit confused about the text prompts used for DDIM inversion. 

During inference, the input condition $I^g$ needs to undergo DDIM inversion with a text prompt describing the condition image. It works fine the natural images, however a little bit tricky for some condition modalities (e.g, depth map). I use prompts like "depth map of ..." for depth map condition, for example, but hard to reproduce the results showcased in the paper (Fig. 4). 

Could you please share some tips for designing text prompts that are used during DDIM inversion of $I^g$? If possible, please provide further some examples or suggested prompts. Thank you in advance!

**Comment by Maeyon-Z** [comment]
您好！请问这个问题您解决了吗？
