### ISSUE TITLE
Point cloud projection as control signal

### ISSUE THREAD

**Issue by ntaquan0125** [genforce/freecontrol#11]
Dear authors,

Thank you for the interesting paper.

The paper's teaser mentions that it supports 2D projections of point clouds. But I don't see any additional result other than that.

Could you show me how to run the code given this type of control signal?
The projected map should have depth values or a color map of depth?

**Comment by SichengMo** [comment]
Thanks for reaching out. Our method can take the 2D visualization of the 3D point clouds as the structure condition. You can take a screenshot of your viewport and upload it to our Gradio demo. Then choose "None" as the condition type, it will use the input image as the condition directly. 

We indeed have more examples of 3D point clouds in our paper: Figure 5 in our [CVPR version](https://openaccess.thecvf.com/content/CVPR2024/html/Mo_FreeControl_Training-Free_Spatial_Control_of_Any_Text-to-Image_Diffusion_Model_with_CVPR_2024_paper.html). Also our follow up work [Ctrl-X ](https://genforce.github.io/ctrl-x/)can work well on those conditions with much faster inference speed.

**Comment by ntaquan0125** [comment]
Thank you for the answer
