### ISSUE TITLE
求作者大大帮忙看一下，为什么生成的结果会这样啊，直接运行的，没有做什么改动

### ISSUE THREAD

**Issue by Maeyon-Z** [genforce/freecontrol#12]
<img width="1371" alt="Snipaste_2024-07-11_20-11-56" src="https://github.com/genforce/freecontrol/assets/94529454/5c9362f7-4e85-45eb-92e6-68958507f3dc">

**Comment by SichengMo** [comment]
Thanks for reaching out. Our method heavily relies on the semantic understanding of the input conditions. Therefore it might fail on the input condition with missing structure. The results should be fine if you use "None" as the condition type (will directly use the input image as the condition) or try other images that work well with the canny edge extractor.  

我们的方法依赖于Stable Diffusion模型对输入图像的理解能力，如果输入图像是残缺的，通常会导致我们的方法失败。 你可以选择“None”作为condition type或者换一张能提取出比较完整合理的edge map的图。

**Comment by Maeyon-Z** [comment]
您好，我这边选了“None”作为condition type，生成出来了两张结果还是效果不太行，右图是没有控制干预的生成结果，这张图看起来效果也不太对，我用同样的权重在webui下不做任何控制直接生成效果是正常的，这就说明权重文件没有问题，想请问一下您觉着问题可能出现在哪里？
<img width="1462" alt="123" src="https://github.com/user-attachments/assets/4d520b24-509f-4484-98b9-37c61ee03371">

**Comment by SichengMo** [comment]
您好，我这边完全按照repo中的instruction重新安装了一次repo. 如果完全按照我们的步骤，应该能得到这样的结果。
<img width="1533" alt="freecontrol-defult" src="https://github.com/user-attachments/assets/2fcffe61-7922-46a3-a52c-aabcd524952c">

**Comment by Maeyon-Z** [comment]
感谢您的回复，我这边再检查一下
