### ISSUE TITLE
SDXL version

### ISSUE THREAD

**Issue by Fire-friend** [genforce/freecontrol#15]
可以开源SDXL版本吗，或者作者能否提供注意力注入的细节，有什么参考项目可以推荐辅助复现吗

**Comment by SichengMo** [comment]
你好，我们的SDXL版本需要大约43GB的GPU memory去运行，所以我们暂时没有开源我们在sdxl上的实现。关于注意力注入，有更详细的问题吗

**Comment by Hongbin98** [comment]
Hello @SichengMo, I noticed that you have released the code for sdxl-verision. However, it throws the error 'sample_semantic_basis.py': [Errno 2] No such file or directory' when I try to use it. Furthermore, an additional error is 'sample_semantic_bases.py: error: unrecognized arguments: --mask_obj car'.
Will there be any updates to this part in the future?

**Comment by fmu2** [comment]
The SDXL pipeline is currently experimental. An update will be pushed soon. Stay tuned.

**Comment by fmu2** [comment]
The SDXL pipeline has been updated. You are welcome to try it out.

**Comment by Fire-friend** [comment]
Thank you very much for your efforts!

**Comment by Hongbin98** [comment]
> 你好，我们的SDXL版本需要大约43GB的GPU memory去运行，所以我们暂时没有开源我们在sdxl上的实现。关于注意力注入，有更详细的问题吗

I wonder if a single A100-40GB (< 43GB) is able to run the SDXL version of Freecontrol? @SichengMo @fmu2

**Comment by SichengMo** [comment]
For our current code, you could use a smaller image resolution (768) to run our sdxl version. We will try to reduce the GPU memory usage in the next update.

**Comment by Hongbin98** [comment]
Thanks for your reply on time and contributions to the community :)

**Comment by SichengMo** [comment]
You are also welcomed to try our new method [Ctrl-X](https://github.com/genforce/ctrl-x)! It is a training-free and guidance-free method that allows you controlling the sturcture and appearance at the same time and outpforming FreeControl in terms of controbility and inference cost. It reuqires only **3.8GB** memory to run our SDXL version!

**Comment by Hongbin98** [comment]
Thanks for your sharing, I will check it and cite your paper in my future work~
