### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by wangqixun** [genforce/freecontrol#2]
大佬牛逼！！！等不及了！！！希望支持一下diffusers

**Comment by SichengMo** [comment]
Thanks! The code we plan to release will be built on diffusers.

**Comment by wangqixun** [comment]
催更啦催更啦！！！！！
InstantID虽然支持了Multi-Controlnet，但是总觉得不够优雅，一直想和free control做适配
https://github.com/InstantID/InstantID
https://huggingface.co/spaces/InstantX/InstantID

**Comment by SichengMo** [comment]
感谢！ 我们这周就能开源出来。

Thanks for asking! There's a delay in the code release plan, and we're working on it now. It will be available before this Friday.

**Comment by SichengMo** [comment]
The code is released. You are welcome to try our code :)
