### ISSUE TITLE
Discussions on SDXL and other latest SD models

### ISSUE THREAD

**Issue by Hongbin98** [genforce/freecontrol#21]
dear authors,

Recently, I empirically found that PCA guidance is often unable to guide the diffusion process based on SDXL, i.e., the result is similar to the 'without control' setting. Do you meet similar questions before? Are there any suggestions?
I think this is a specific problem of sdxl instead of freecontrol because it works well based on sd2.1

Another question is if freecontrol could also work well based on the latest SD model like SD3.X?

Thanks

**Comment by SichengMo** [comment]
Thanks for reaching out! We empirically find that SDXL could share the same hyper-parameters. You may increase the guidance weight if you find the control image is very close to the uncontrolled one. 

For more stable and faster controlling method on SDXL, you could also use our following-up work [Ctrl-X](https://github.com/genforce/ctrl-x). We have plans to make Ctrl-X to support SD3 and FLUX.
