### ISSUE TITLE
Code release plan

### ISSUE THREAD

**Issue by maxin-cn** [genforce/freecontrol#5]
Thank you for your fantastic and interesting work. Could you kindly let me know when you intend to release your code? Many thanks.

**Comment by SichengMo** [comment]
Thanks for asking. We are working on cleaning the code and creating a Gradio interface. We plan to release the code either at the end of January or early February.

**Comment by gungui98** [comment]
@SichengMo any update for the code yet?

**Comment by SichengMo** [comment]
Thanks for asking! There's a delay in the code release plan, and I'm working on it now. It will be available before this Friday.

**Comment by SichengMo** [comment]
The code is released. You are welcome to try our code :)
