### ISSUE TITLE
0.0 seconds (IMPORT FAILED)

### ISSUE THREAD

**Issue by ivanoff13** [genforce/freecontrol#9]
0.0 seconds (IMPORT FAILED): F:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Diffusers-freecontrol

**Comment by SichengMo** [comment]
Please submit the issue to the correct repo. I believe this belongs to :https://github.com/kijai/ComfyUI-Diffusers-freecontrol
